### ISSUE TITLE
Extraction errors for BF2 PC "amb" sounds

### ISSUE THREAD

**Issue by cmathew** [phantom567459/SoundFMVextractor#13]
I am seeing two types of errors when extracting per-level ambient tracks . Looking at `tat.lvl` for example, extracting gives `tat_amb_cantina`, `tat_amb_drip`, `tat_amb_desert`, and `tat_amb_desertwind`. 

Of these, `tat_amb_cantina` and `tat_amb_drip` seem to have some kind of interlacing issue. Each is nominally a stereo track but seems to actually consist of two alternating stereo steams. I'd guess that BF2 uses four-channel audio, and samples are getting mixed together.

The remaining "amb" sound files exhibit a second issue. Neither ffmpeg or vgmstream understand them, resulting in playback errors. I would guess that they are incorrect or corrupted in some way.

**Comment by BAD-AL** [comment]
That the extracted sound files are the quadraphonic combined files should not be considered a defect.
There was a de-interlacer program created to split up the quadraphonic files into front and back tracks. 
It's source repo is here:
https://github.com/marler8997/audio-deinterlacer

The program is included in the SWBF Sound Env download package over on Moddb:
https://www.moddb.com/games/star-wars-battlefront-ii/downloads/swbf1-swbf2-soundenv-for-modders
The also included 'WavHelper' program has a right-click option to run the de-interlacer.
